/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;
import java.util.*;
import java.time.*;
import java.time.format.DateTimeFormatter;

public class ContatoView {
    Scanner scan = new Scanner(System.in);
    Contato c = new Contato();
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private ArrayList<Contato> lista = new ArrayList<>();

    public static void main(String[] args) {
        ContatoView view = new ContatoView();
        view.menu();
    }

    public void menu (){
        
        String menu = """
            1 - Cadastrar novo contato
            2 - Remover contato
            3 - Editar contato
            4 - Listar contatos
            5 - Procurar contato
            9 - Finalizar
                
            Digite a opcao desejada:
            """;
        
            int n = 0;

            while(n!=9){
                System.out.println("G E S T A O  D E  C O N T A T O S");
                System.out.println("");
                System.out.println(menu);
                n = Integer.parseInt(scan.nextLine());
                try{

                    switch(n){
                    case 1:
                        cadastrar();
                    break;

                    case 2: 
                        remover(c.getId());
                    break;
                    case 3:
                        editar(c.getId());
                    break;
                    case 4:
                        listar();
                    break;
                    case 5:
                        procurar(c.getId());
                    break;
                    case 9:
                    break;
                    default:
                        System.err.println( "Erro: Escolha uma opcao valida" );
                    break; 
                    }
                }catch (Exception e) { 
                    System.err.println( "Erro: " + e.getMessage() );
            }
        }
    }

    public void cadastrar(){
        System.out.println("C A D A S T R A R  C O N T A T O");
        System.out.println("");
        System.out.println("Digite o nome: ");
        String nome = scan.nextLine();

        System.out.println("Digite o telefone: ");
        String telefone = scan.nextLine();

        System.out.println("Digite o email: ");
        String email = scan.nextLine();

        System.out.println("Digite o nascimento: ");
        String nascimento = scan.nextLine();

        c.setNome(nome);
        c.setTelefone(telefone);
        c.setEmail(email);
        c.setNascimento( LocalDate.parse(nascimento, dtf) );

        lista.add( c );

    }

    public void remover(long id){
    	
    }

    public void editar(long id){

    }

    public void listar(){
    	if(lista.isEmpty()) {
    		System.out.println("Não possuí nenhum contato salvo na agenda");
    	}
    	
        for(Contato c : lista){
            System.out.println(c.getNome());
            System.out.println(c.getTelefone());
            System.out.println(c.getEmail());
            System.out.println(c.getNascimento());
        }
    }

    public void procurar(long id){
    	
    }
    
}
