/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;
import java.util.*;
import java.time.*;
import java.time.format.DateTimeFormatter;

public class ContatoView {
    Scanner scan = new Scanner(System.in);
    Contato c = new Contato();
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private ArrayList<Contato> lista = new ArrayList<>();
     
    static long idContador = 0;

    public static void main(String[] args) {
        ContatoView view = new ContatoView();
        view.menu();
    }

    public void menu (){
        
        String menu = """
            1 - Cadastrar novo contato
            2 - Remover contato
            3 - Editar contato
            4 - Listar contatos
            5 - Procurar contato
            9 - Finalizar
                
            Digite a opcao desejada:
            """;
            int n = 0;

            while(n!=9){
                System.out.println("G E S T A O  D E  C O N T A T O S");
                System.out.println("");
                System.out.println("");
                System.out.println(menu);
                n = scan.nextInt();
                scan.nextLine();
                n = scan.nextInt();
                scan.nextLine();
                try{

                    switch(n){
                    case 1:
                        cadastrar();
                    break;

                    case 2: 
                        remover(c.getId());
                    break;
                    case 3:
                        editar(c.getId());
                        editar(c.getId());
                    break;
                    case 4:
                        listar();
                    break;
                    case 5:
                        procurar(c.getId());
                    break;
                    case 9:
                    break;
                    default:
                        System.err.println( "Erro: Escolha uma opcao valida" );
                    break; 
                    }
                }catch (Exception e) { 
                    System.err.println( "Erro: " + e.getMessage() );
            }
        }
    }

    public void cadastrar(){
        Contato c = new Contato();
        idContador = idContador + 1;
        c.setId(idContador);
        
        System.out.println("C A D A S T R A R  C O N T A T O");
        System.out.println("Digite o nome: ");
        String nome = scan.nextLine();

        System.out.println("Digite o telefone: ");
        String telefone = scan.nextLine();

        System.out.println("Digite o email: ");
        String email = scan.nextLine();

        System.out.println("Digite o nascimento: ");
        String nascimento = scan.nextLine();

        c.setNome(nome);
        c.setTelefone(telefone);
        c.setEmail(email);
        c.setNascimento( LocalDate.parse(nascimento, dtf) );

        lista.add( c );

    }

    public void remover(long id){
    	System.out.println("Digite o Id do número que você deseja remover:");
        long n = scan.nextLong();

        for(Contato c : lista){
            if(c.getId() == n){
                lista.remove(c);
            }
        }
        System.out.println("O contato do Id " + n + " foi removido");
    }

    public void editar(long id){
        System.out.println("Digite o Id do número que você deseja editar:");
        long n = scan.nextLong();
        scan.nextLine();

        System.out.println("(N) Nome");
        System.out.println("(T) Telefone");
        System.out.println("(E) Email");
        System.out.println("(D) Data de nascimento");
        System.out.println("Qual dado você quer editar? ");
        String dado = scan.nextLine().toUpperCase();

    for (Contato c : lista) {
        if (c.getId() == n) {
            if (dado.equals("N")) {
                System.out.println("Novo nome:");
                c.setNome(scan.nextLine());
            } else if (dado.equals("T")) {
                System.out.println("Novo telefone:");
                c.setTelefone(scan.nextLine());
            } else if (dado.equals("D")) {
                System.out.println("Nova data (dd/mm/aaaa):");
                String dt = scan.nextLine();
                c.setNascimento(LocalDate.parse(dt, dtf)); 
            }
            System.out.println("Contato atualizado!");
        }
    }
}

    public void listar(){
    	if(lista.isEmpty()) {
    		System.out.println("Não possuí nenhum contato salvo na agenda");
    	}
    	
        for(Contato c : lista){
            System.out.println("ID: " + c.getId());
            System.out.println("Nome: " + c.getNome());
            System.out.println("Telefone: " + c.getTelefone());
            System.out.println("Email: " + c.getEmail());
            System.out.println("Data de nascimento: "+ c.getNascimento());
    	    if(lista.isEmpty()) {
    		    System.out.println("Não possuí nenhum contato salvo na agenda");
    	    }
        }
    }

    public void procurar(long id){
        Boolean encontrado = false;
        System.out.println("Digite o id do número que deseja procurar: ");
        Long idProcurar = scan.nextLong();
    	for(Contato c : lista){
            
            if (idProcurar.equals(id)){
                System.out.println("");
                System.out.println("ID: " + c.getId());
                System.out.println("Nome: " + c.getNome());
                System.out.println("Telefone: " + c.getTelefone());
                System.out.println("Email: " + c.getEmail());
                System.out.println("Data de nascimento: "+ c.getNascimento());
                encontrado = true;
            }
        }
        if(!encontrado){
            System.out.println("O Id não está na lista de contato!");
        }
        
    }
    
}
